"""Unit tests for Markdown and JSON report renderers."""

from __future__ import annotations

from datetime import datetime, timezone
import json
import pytest

from app.engine.scanner import ScanResult
from app.report import render_json, render_markdown
from app.store import ScanRecord, SecretLeakError


def _make_dummy_record() -> ScanRecord:
    findings = [
        {
            "id": "find-1",
            "check": "bola",
            "severity": "CRITICAL",
            "confidence": 0.9,
            "title": "BOLA on Orders",
            "endpoint": "/orders/{id}",
            "method": "GET",
            "attacker_identity": "userB",
            "owasp_category": "API1:2023",
            "explanation": "userB accessed userA's order.",
            "remediation": "Validate owner ID against token subject.",
            "evidence": {
                "curl_command": "curl -H 'Authorization: Bearer ***REDACTED***' http://target/orders/101",
                "baseline_response": {"status_code": 403},
                "attack_response": {"status_code": 200},
                "response_diff": {
                    "changed_fields": ["id", "items"],
                    "masked_values": ["***REDACTED***"],
                },
            },
        },
        {
            "id": "find-2",
            "check": "data_exposure",
            "severity": "HIGH",
            "confidence": 0.85,
            "title": "Excessive Data Exposure on Users",
            "endpoint": "/users/{id}",
            "method": "GET",
            "attacker_identity": "anonymous",
            "owasp_category": "API3:2023",
            "explanation": "Sensitive fields leaked in response.",
            "remediation": "Use DTOs to filter response fields.",
            "evidence": {
                "curl_command": "curl http://target/users/42",
                "baseline_response": {"status_code": 200},
                "attack_response": {"status_code": 200},
                "response_diff": {
                    "changed_fields": ["password_hash"],
                    "masked_values": ["***MASKED_SSN***"],
                },
            },
        },
    ]

    result = ScanResult(
        findings=findings,
        surface=[
            {"endpoint": "/orders/{id}", "method": "GET", "score": 90},
            {"endpoint": "/users/{id}", "method": "GET", "score": 75},
        ],
        matrix={
            "identities": ["userA", "userB"],
            "cells": [
                {"endpoint": "/orders/{id}", "method": "GET", "identity": "userA", "expected_status": 200, "object_id": "101"},
                {"endpoint": "/orders/{id}", "method": "GET", "identity": "userB", "expected_status": 403, "object_id": "101"},
            ],
        },
        matrix_summary={"total_cells": 2, "allow_count": 1, "deny_count": 1},
        plan_stats={"total_generated": 10, "total_kept": 2},
        notes=["Test execution telemetry note 1", "Skipped endpoint X"],
        summary={
            "total_findings": 2,
            "by_severity": {"CRITICAL": 1, "HIGH": 1, "MEDIUM": 0, "LOW": 0, "INFO": 0},
            "by_check": {"bola": 1, "data_exposure": 1},
            "endpoints_total": 2,
            "requests_sent": 25,
            "request_budget": 100,
            "cases_generated": 10,
            "cases_kept": 2,
            "reproduced_count": 1,
            "downgraded_count": 0,
            "max_risk_score": 90,
            "top_findings": [
                {"title": "BOLA on Orders", "severity": "CRITICAL", "endpoint": "/orders/{id}"},
                {"title": "Excessive Data Exposure on Users", "severity": "HIGH", "endpoint": "/users/{id}"},
            ],
        },
        requests_sent=25,
        duration_seconds=3.45,
    )

    return ScanRecord(
        id="test-scan-uuid-1234",
        status="completed",
        created_at=datetime(2026, 9, 25, 0, 0, 0, tzinfo=timezone.utc),
        started_at=datetime(2026, 9, 25, 0, 0, 1, tzinfo=timezone.utc),
        finished_at=datetime(2026, 9, 25, 0, 0, 4, tzinfo=timezone.utc),
        config_public={
            "base_url": "http://target-api:9000",
            "spec_source": "url:target-api:9000",
            "identities": [{"name": "userA", "role": "user"}, {"name": "userB", "role": "user"}],
        },
        progress={"seq": 10, "status": "completed", "percent": 100},
        result=result,
    )


def test_markdown_report_determinism_and_content() -> None:
    """Markdown rendering is deterministic, groups by severity, and contains required sections."""
    record = _make_dummy_record()

    render1 = render_markdown(record)
    render2 = render_markdown(record)

    # Determinism across multiple renders
    assert render1 == render2

    # Required sections and content
    assert "# SentinelAPI Security Scan Report" in render1
    assert "Generated by SentinelAPI. Only run against systems you are authorized to test." in render1
    assert "## Scan Metadata" in render1
    assert "## Executive Summary" in render1
    assert "## Authorization Matrix" in render1
    assert "## Detailed Findings" in render1
    assert "### CRITICAL Findings" in render1
    assert "### HIGH Findings" in render1
    assert "## Scan Notes and Limitations" in render1

    # Matrix table verification
    assert "| `/orders/{id}` | GET | **userA** | 200 | `101` |" in render1
    assert "| `/orders/{id}` | GET | **userB** | 403 | `101` |" in render1

    # Curl block verification
    assert "```bash\ncurl -H 'Authorization: Bearer ***REDACTED***'" in render1


def test_markdown_report_asserts_no_secrets() -> None:
    """Markdown generator refuses to render raw JWTs or unredacted passwords."""
    record = _make_dummy_record()
    # Inject a raw unredacted secret into evidence
    assert record.result is not None
    record.result.findings[0]["evidence"]["curl_command"] = "curl -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.fake' http://target"

    with pytest.raises(SecretLeakError, match="Bearer ey"):
        render_markdown(record)


def test_json_report_roundtrip_and_no_secrets() -> None:
    """JSON report round-trips cleanly and verifies absence of secrets."""
    record = _make_dummy_record()
    raw_json = render_json(record)

    # Valid JSON parseable
    parsed = json.loads(raw_json)
    assert parsed["id"] == "test-scan-uuid-1234"
    assert parsed["status"] == "completed"
    assert len(parsed["findings"]) == 2
    assert parsed["summary"]["total_findings"] == 2

    # Inject raw password leak
    assert record.result is not None
    record.result.findings[0]["evidence"]["raw_leak"] = {"password": "unredacted_password_123"}
    with pytest.raises(SecretLeakError, match="Unredacted credential"):
        render_json(record)
