/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scans
         * @description List historical scan summaries ordered from newest to oldest.
         */
        get: operations["list_scans"];
        put?: never;
        /**
         * Submit Scan
         * @description Submit a new security scan job.
         *
         *     Accepts target specification and identity credentials. Validates scope,
         *     schedules execution in the background, and returns tracking URLs.
         */
        post: operations["submit_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan
         * @description Retrieve detailed scan execution metadata, public config, and summary metrics.
         */
        get: operations["get_scan"];
        put?: never;
        post?: never;
        /**
         * Delete Scan
         * @description Delete a scan record and its artifacts from storage.
         */
        delete: operations["delete_scan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Findings
         * @description Query and filter detected findings for a completed scan.
         */
        get: operations["get_scan_findings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Finding
         * @description Retrieve full details of a specific finding by ID.
         */
        get: operations["get_scan_finding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/surface": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Surface
         * @description Retrieve mapped attack surface endpoints and risk prioritizations.
         */
        get: operations["get_scan_surface"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Matrix
         * @description Retrieve multi-identity authorization matrix and heatmap statistics.
         */
        get: operations["get_scan_matrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Notes
         * @description Retrieve execution telemetry, skipped tests, and check notes.
         */
        get: operations["get_scan_notes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Scan Events
         * @description Subscribe to real-time Server-Sent Events (SSE) for progress updates.
         */
        get: operations["stream_scan_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Scan
         * @description Cancel an ongoing scan job gracefully, invoking shielded resource cleanup.
         */
        post: operations["cancel_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/report.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Report Json
         * @description Download full scan report as a JSON file attachment.
         */
        get: operations["get_scan_report_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/report.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Report Md
         * @description Download executive scan report as a Markdown file attachment.
         */
        get: operations["get_scan_report_md"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI feature detection
         * @description Returns whether the AI analyst is configured. Never returns the LLM API key. Always available.
         */
        get: operations["get_ai_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/findings/{finding_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain a finding with AI
         * @description Generate an AI explanation for a specific finding. Returns 503 when AI is not configured, 409 if scan is not finished, 422 for invalid framework_hint, 429 when call cap is reached.
         */
        post: operations["explain_finding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/explain-top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain the top-N findings
         * @description Explain the top-N findings by severity then confidence. Skips already-analyzed findings. Stops at the call cap and reports skipped.
         */
        post: operations["explain_top_findings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}/ai-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate AI executive summary
         * @description Generate an AI executive summary for a completed scan. Returns 503 if unconfigured, 409 if scan is not finished, 429 if cap reached.
         */
        post: operations["generate_ai_summary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Healthcheck endpoint reporting service operational status.
         */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scope
         * @description Return the list of explicitly allow-listed scan target hosts.
         */
        get: operations["get_scope"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AiAnalysis
         * @description Validated output schema for LLM-generated or template-based analysis.
         */
        AiAnalysis: {
            /**
             * Plain Explanation
             * @default
             */
            plain_explanation: string;
            /**
             * Business Impact
             * @default
             */
            business_impact: string;
            /**
             * Attacker Scenario
             * @default
             */
            attacker_scenario: string;
            /** Remediation Steps */
            remediation_steps?: string[];
            /**
             * Code Fix Example
             * @default
             */
            code_fix_example: string;
            /**
             * Code Language
             * @default generic
             */
            code_language: string;
            /** Verification Steps */
            verification_steps?: string[];
            /**
             * Source
             * @default template
             */
            source: string;
            /** Model */
            model?: string | null;
            /**
             * Prompt Version
             * @default v1
             */
            prompt_version: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Warning */
            warning?: string | null;
        };
        /**
         * AiStatusResponse
         * @description Response for GET /ai/status.
         */
        AiStatusResponse: {
            /** Enabled */
            enabled: boolean;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Max Calls Per Scan */
            max_calls_per_scan: number;
        };
        /**
         * AiSummaryResponse
         * @description Response for POST /scans/{id}/ai-summary.
         */
        AiSummaryResponse: {
            /** Text */
            text: string;
            /** Source */
            source: string;
            /** Model */
            model: string | null;
            /** Generated At */
            generated_at: string;
            /** Calls Used */
            calls_used: number;
        };
        /** CancelResponse */
        CancelResponse: {
            /** Scan Id */
            scan_id: string;
            /** Cancelled */
            cancelled: boolean;
            /** Status */
            status: string;
        };
        /**
         * ExplainRequest
         * @description Request body for POST /scans/{id}/findings/{fid}/explain.
         */
        ExplainRequest: {
            /**
             * Framework Hint
             * @default generic
             */
            framework_hint: string;
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
        };
        /**
         * ExplainTopResponse
         * @description Response for POST /scans/{id}/explain-top.
         */
        ExplainTopResponse: {
            /** Analyses */
            analyses: {
                [key: string]: unknown;
            }[];
            /** Skipped Count */
            skipped_count: number;
            /** Calls Used */
            calls_used: number;
            /** Calls Remaining */
            calls_remaining: number;
        };
        /** FindingsListResponse */
        FindingsListResponse: {
            /** Findings */
            findings: {
                [key: string]: unknown;
            }[];
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityConfig
         * @description Configuration specification for a test identity persona.
         */
        IdentityConfig: {
            /**
             * Name
             * @description Unique persona name (e.g. userA, admin)
             */
            name: string;
            /**
             * Role
             * @description Default role if not specified in JWT claims
             * @default user
             */
            role: string;
            /**
             * Username
             * @description Login username or identifier
             */
            username: string;
            /**
             * Password
             * Format: password
             * @description Login password strictly protected as SecretStr
             */
            password: string;
            /**
             * Login Path
             * @description Authentication endpoint path
             * @default /auth/login
             */
            login_path: string;
            /**
             * Token Key
             * @description JSON response key containing token
             * @default access_token
             */
            token_key: string;
            /**
             * Username Field
             * @description Form field or JSON key for username
             * @default username
             */
            username_field: string;
            /**
             * Password Field
             * @description Form field or JSON key for password
             * @default password
             */
            password_field: string;
        };
        /** MatrixResponse */
        MatrixResponse: {
            /** Identities */
            identities: string[];
            /** Cells */
            cells: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** NotesResponse */
        NotesResponse: {
            /** Notes */
            notes: string[];
            /** Total */
            total: number;
        };
        /**
         * ScanConfig
         * @description Complete specification required to execute a security scan.
         */
        ScanConfig: {
            /**
             * Spec Url
             * @description URL to remote OpenAPI specification
             */
            spec_url?: string | null;
            /**
             * Spec Inline
             * @description Inline OpenAPI specification dictionary
             */
            spec_inline?: {
                [key: string]: unknown;
            } | null;
            /**
             * Base Url
             * @description Base URL of target API
             */
            base_url: string;
            /**
             * Identities
             * @description List of test identity personas
             */
            identities: components["schemas"]["IdentityConfig"][];
            /**
             * Enabled Checks
             * @description Optional subset of checks to execute
             */
            enabled_checks?: string[] | null;
            /**
             * Test Case Budget
             * @description Budget cap for generated test cases
             * @default 150
             */
            test_case_budget: number;
            /**
             * Max Requests
             * @description Maximum total requests permitted for the scan
             * @default 1000
             */
            max_requests: number;
            /**
             * Sample Bodies
             * @description Sample request bodies for POST/PUT resource mutations
             */
            sample_bodies?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Use Ai Hints
             * @description When true (and AI is configured), use LLM to suggest extra test coverage flags
             * @default false
             */
            use_ai_hints: boolean;
        };
        /** ScanDetailResponse */
        ScanDetailResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Progress */
            progress: {
                [key: string]: unknown;
            };
            /** Config Public */
            config_public: {
                [key: string]: unknown;
            };
            /** Summary */
            summary?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /**
             * Notes Count
             * @default 0
             */
            notes_count: number;
        };
        /** ScanSubmitResponse */
        ScanSubmitResponse: {
            /** Scan Id */
            scan_id: string;
            /** Status */
            status: string;
            /** Status Url */
            status_url: string;
            /** Events Url */
            events_url: string;
        };
        /** ScanSummaryItem */
        ScanSummaryItem: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Base Url */
            base_url: string;
            /** Total Findings */
            total_findings: number;
            /** By Severity */
            by_severity: {
                [key: string]: number;
            };
        };
        /** SurfaceResponse */
        SurfaceResponse: {
            /** Endpoints */
            endpoints: {
                [key: string]: unknown;
            }[];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_scans: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSummaryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_scan: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_findings: {
        parameters: {
            query?: {
                severity?: string | null;
                check?: string | null;
                min_confidence?: number | null;
                sort?: string;
                order?: string;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_finding: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_surface: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurfaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_matrix: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatrixResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_notes: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_scan_events: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scan: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_report_json: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_report_md: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_status: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_finding: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_top_findings: {
        parameters: {
            query?: {
                /** @description Number of findings to explain */
                n?: number;
                framework_hint?: string;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainTopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_ai_summary: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_scope: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
