"""Report generators for SentinelAPI scan records (Markdown and JSON)."""

from __future__ import annotations

import json
from typing import Any

from app.store import ScanRecord, assert_no_secrets

SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]


def render_json(record: ScanRecord) -> str:
    """Render full scan results as pretty-printed JSON.

    Guarded by assert_no_secrets.
    """
    data: dict[str, Any] = {
        "id": record.id,
        "status": record.status,
        "created_at": record.created_at.isoformat() if hasattr(record.created_at, "isoformat") else record.created_at,
        "started_at": record.started_at.isoformat() if hasattr(record.started_at, "isoformat") else record.started_at,
        "finished_at": record.finished_at.isoformat() if hasattr(record.finished_at, "isoformat") else record.finished_at,
        "config": record.config_public,
        "summary": record.result.summary if record.result else {},
        "findings": record.result.findings if record.result else [],
        "surface": record.result.surface if record.result else [],
        "matrix": record.result.matrix if record.result else {},
        "matrix_summary": record.result.matrix_summary if record.result else {},
        "plan_stats": record.result.plan_stats if record.result else {},
        "notes": record.result.notes if record.result else [],
        "error": record.error,
    }
    rendered = json.dumps(data, indent=2, sort_keys=True, default=str)
    assert_no_secrets(rendered)
    return rendered


def render_markdown(record: ScanRecord) -> str:
    """Render deterministic Markdown report from a ScanRecord.

    Output is deterministically sorted and guaranteed secret-free.
    """
    res = record.result
    summary = res.summary if res else {}
    findings = res.findings if res else []
    matrix = res.matrix if res else {}
    notes = res.notes if res else []
    config = record.config_public or {}

    lines: list[str] = []

    # Header and Notice
    lines.append("# SentinelAPI Security Scan Report")
    lines.append("> Generated by SentinelAPI. Only run against systems you are authorized to test.\n")

    # 1. Metadata Table
    lines.append("## Scan Metadata\n")
    lines.append("| Property | Value |")
    lines.append("| :--- | :--- |")
    lines.append(f"| **Scan ID** | `{record.id}` |")
    lines.append(f"| **Target Host** | `{config.get('base_url', 'N/A')}` |")
    lines.append(f"| **Spec Source** | `{config.get('spec_source', 'N/A')}` |")
    lines.append(f"| **Status** | `{record.status}` |")
    lines.append(f"| **Started At** | {record.started_at or 'N/A'} |")
    lines.append(f"| **Finished At** | {record.finished_at or 'N/A'} |")
    duration = f"{res.duration_seconds:.2f}s" if res else "N/A"
    lines.append(f"| **Duration** | {duration} |")
    requests_sent = res.requests_sent if res else 0
    lines.append(f"| **Requests Sent** | {requests_sent} |")
    lines.append("")

    # 2. Executive Summary
    lines.append("## Executive Summary\n")
    by_severity = summary.get("by_severity", {})
    lines.append("### Findings by Severity\n")
    lines.append("| Severity | Count |")
    lines.append("| :--- | :--- |")
    for sev in SEVERITY_ORDER:
        cnt = by_severity.get(sev, 0)
        lines.append(f"| **{sev}** | {cnt} |")
    lines.append("")

    top_findings = summary.get("top_findings", [])
    if top_findings:
        lines.append("### Key Risks\n")
        for i, tf in enumerate(top_findings, 1):
            title = tf.get("title", "Unknown")
            sev = tf.get("severity", "UNKNOWN")
            ep = tf.get("endpoint", "")
            lines.append(f"{i}. **[{sev}]** {title} at `{ep}`")
        lines.append("")

    # 3. Authorization Matrix
    lines.append("## Authorization Matrix\n")
    cells = matrix.get("cells", [])
    identities = matrix.get("identities", [])
    if cells:
        # Sort cells deterministically
        sorted_cells = sorted(cells, key=lambda c: (c.get("endpoint", ""), c.get("method", ""), c.get("identity", "")))
        lines.append(f"*Evaluated {len(identities)} identities across {len(sorted_cells)} authorization cells.*\n")
        lines.append("| Endpoint | Method | Identity | Expected | Discovered Object |")
        lines.append("| :--- | :--- | :--- | :--- | :--- |")
        for cell in sorted_cells:
            ep = cell.get("endpoint", "")
            method = cell.get("method", "")
            ident = cell.get("identity", "")
            exp = cell.get("expected_status", "N/A")
            obj = cell.get("object_id") or "-"
            lines.append(f"| `{ep}` | {method} | **{ident}** | {exp} | `{obj}` |")
        lines.append("")
    else:
        lines.append("*No authorization matrix data recorded.*\n")

    # 4. Detailed Findings (Grouped by Severity, sorted by endpoint then title)
    lines.append("## Detailed Findings\n")
    if not findings:
        lines.append("No security vulnerabilities were identified.\n")
    else:
        # Group by severity
        grouped: dict[str, list[dict[str, Any]]] = {s: [] for s in SEVERITY_ORDER}
        for f in findings:
            sev = f.get("severity", "INFO")
            if sev in grouped:
                grouped[sev].append(f)
            else:
                grouped.setdefault("INFO", []).append(f)

        for sev in SEVERITY_ORDER:
            group = grouped[sev]
            if not group:
                continue

            lines.append(f"### {sev} Findings\n")
            # Deterministic ordering within severity group
            group_sorted = sorted(group, key=lambda f: (f.get("endpoint", ""), f.get("method", ""), f.get("title", "")))

            for f in group_sorted:
                title = f.get("title", "Finding")
                ep = f.get("endpoint", "")
                method = f.get("method", "")
                evidence = f.get("evidence") or {}
                attacker = (
                    f.get("attacker_identity")
                    or (evidence.get("request") or {}).get("identity")
                    or "anonymous"
                )
                conf = f.get("confidence", "UNKNOWN")
                owasp = f.get("owasp_id") or f.get("owasp_category") or ""
                explanation = f.get("explanation", "")
                remediation = f.get("fix_hint") or f.get("remediation") or ""

                lines.append(f"#### {title}")
                lines.append(f"- **Endpoint**: `{method} {ep}`")
                lines.append(f"- **Attacker Identity**: `{attacker}`")
                lines.append(f"- **Severity / Confidence**: `{sev}` / `{conf}`")
                if owasp:
                    lines.append(f"- **OWASP Category**: {owasp}")
                lines.append("")
                lines.append(f"**Explanation**:\n{explanation}\n")

                # Evidence summary
                diff = evidence.get("response_diff") or {}
                base_resp = evidence.get("baseline_response") or {}
                atk_resp = evidence.get("attack_response") or {}

                lines.append("**Evidence Summary**:")
                base_status = base_resp.get("status_code", "N/A")
                atk_status = atk_resp.get("status_code", "N/A")
                lines.append(f"- Expected Status: `{base_status}` | Actual Status: `{atk_status}`")

                changed_fields = diff.get("changed_fields") or diff.get("changed_keys") or []
                if changed_fields:
                    lines.append(f"- Changed Fields: `{', '.join(str(cf) for cf in changed_fields)}`")
                masked = diff.get("masked_values") or []
                if masked:
                    lines.append(f"- Masked Evidence: `{', '.join(str(m) for m in masked)}`")
                lines.append("")

                # Curl PoC
                curl = f.get("curl_poc") or evidence.get("curl_command")
                if curl:
                    lines.append("**Reproduction (cURL PoC)**:")
                    lines.append("```bash")
                    lines.append(curl.strip())
                    lines.append("```\n")

                # Fix hint / Remediation
                if remediation:
                    lines.append(f"**Remediation**:\n{remediation}\n")

                lines.append("---\n")

    # 5. Scan Notes and Limitations
    lines.append("## Scan Notes and Limitations\n")
    if notes:
        for note in sorted(set(notes)):
            lines.append(f"- {note}")
    else:
        lines.append("- No operational anomalies or scan limitations recorded.")
    lines.append("- Non-GET privileged endpoints untested without safe sample state.")
    lines.append("- Rate-limit detection is bounded by MAX_RPS throttle limit.\n")

    rendered = "\n".join(lines)
    assert_no_secrets(rendered)
    return rendered
